version: '3'

services:
  db:
    container_name: thread-app-database
    image: postgres
    ports:
      - 8500:5432 # Maps host port 8500 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: 123456
      DATABASE_URL: postgres://postgres:123456@db:5432/threads
    networks:
      - psql-pgql

  api:
    container_name: thread-app-backend
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/threads
    networks:
      - psql-pgql

volumes:
  postgres_data:

networks:
  psql-pgql:
