version: '24.0.9'

services:
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:threads@localhost:8500/threads?schema=public
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  db:
    container_name: thread-app-databse
    image: postgres
    ports:
      - 8500:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data:
